### PR TITLE
feat: integrate indigo IAM and restructure the chart

### PR DESCRIPTION
**Pull request by aldbr**
- The chart is restructured: there is now a clear separation between diracx, diracx-web and tests components (`deployment`/`configmaps`/`jobs`...). I felt it was clearer this way but of course this can be discussed. Let me know if you think differently.
- IAM can be spawned (`/diracx/templates/tests/indigo-iam/deployment.yaml`)
- IAM can be configured (`/diracx/templates/tests/indigo-iam/init-iam/`) with a `job.yaml`: I actually reused the work I did in the DIRAC integration tests. It allows you to create clients, users and groups/subgroups within IAM.
- The admin VO can be manually reconfigured to use IAM instead of Dex: I successfully tested it with `diracx-web`.

closes https://github.com/DIRACGrid/diracx-charts/issues/58

### CODE REVIEW

**Comment by aldbr** [comment]
`IAM` and `init-iam` are correctly executed: https://github.com/DIRACGrid/diracx-charts/actions/runs/7251616761/job/19754329530?pr=66
Now I am going to put back the default values (namely using Dex within diracX and disabling IAM).

**Comment by aldbr** [comment]
Wait before merging, I just resolved the conflicts but IAM does not start anymore and I see some errors in the logs. I will try to resolve that asap.

**Comment by aldbr** [comment]
Update: It seems like these "errors" are not related to this PR.
In any case, it does not prevent the cluster from running.

**Comment by chaen** [comment]
> Are they "expected"? Otherwise, if I enable IAM, it seems to work fine.

they are harmless, it's just because of the boot order (i.e. init-sql starts before mysql is actually ready)

**Comment by aldbr** [comment]
Any feedback? Do we still want to use Indigo IAM?

**Comment by chaen** [comment]
yes we still do: IAM for a "normal VO" and dex for the admin vo. I will brush over that one today and merge it !

**Comment by chrisburr** [comment]
This needs rebasing but otherwise I think this looks good.

**Review by chaen — APPROVED** [review]

**Pull request merged**
